require 'dotenv'

platform :android do
  desc "Lane for android firebase app distribution"
  lane :firebase_distribution do
   Dir.chdir(File.expand_path("..", __dir__)) do
      sh "flutter test"
      sh "flutter clean"
      sh "flutter build apk --release --target lib/main.dart --no-tree-shake-icons"
    end

    firebase_app_distribution(
      app: "1:799349374823:android:5bbb4f89662c1cbc85f9c2",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "abdalrhmanamr14@gmail.com",
      release_notes: "first fastlane test"
    )
  end
end
